kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: ibmc-block-gold
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-claim
  labels:
    app: book-library-postgres-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi